package io.vanillabp.camunda8.quarkus.deployment;

import io.quarkus.arc.deployment.AdditionalBeanBuildItem;
import io.quarkus.deployment.annotations.BuildProducer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.FeatureBuildItem;
import io.vanillabp.camunda8.deployment.Camunda8DeploymentService;
import io.vanillabp.camunda8.quarkus.deployment.config.Camunda8Properties;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8ClientProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8DeploymentServiceProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8MetricsProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8ProcessServiceProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8StartupObserver;
import io.vanillabp.integration.deployment.pipeline.VanillaBpAdapterDeploymentServiceBuildItem;
import io.vanillabp.integration.deployment.processservice.VanillaBpMigratableProcessServiceBuildItem;

/**
 * Quarkus extension of the VanillaBP Camunda 8 adapter. Announces the adapter type and
 * its process-service bean to the VanillaBP Quarkus integration and registers the
 * runtime producer.
 */
class Camunda8IntegrationProcessor {

  private static final String FEATURE = "vanillabp-camunda8";

  /**
   * Builds the {@link VanillaBpMigratableProcessServiceBuildItem} used by the VanillaBP
   * Quarkus integration to determine the process-service class of the Camunda 8
   * adapter.
   *
   * @param properties Camunda 8 build-time properties
   * @param featureProducer Feature build-item producer used to register the extension
   * @return The {@link VanillaBpMigratableProcessServiceBuildItem}
   */
  @BuildStep
  VanillaBpMigratableProcessServiceBuildItem buildProcessServices(
      final Camunda8Properties properties,
      final BuildProducer<FeatureBuildItem> featureProducer) {

    featureProducer.produce(new FeatureBuildItem(FEATURE));

    return VanillaBpMigratableProcessServiceBuildItem
        .builder()
        .adapterType(Camunda8DeploymentService.ADAPTER_TYPE)
        // the announced bean class is registered by the VanillaBP extension - it
        // has to be the producer, not the core process-service class
        .migratableProcessServiceBeanClass(Camunda8ProcessServiceProducer.class.getName())
        .build();

  }

  /**
   * Builds the {@link VanillaBpAdapterDeploymentServiceBuildItem} used by the
   * VanillaBP Quarkus integration to determine and register the deployment-service
   * bean of the Camunda 8 adapter - consumed by the platform's runtime deployment
   * pipeline (readBpmn &rarr; prepareBpmn &rarr; wireBpmn &rarr; deployResources
   * &rarr; startWorkflowProcessing).
   *
   * @return The {@link VanillaBpAdapterDeploymentServiceBuildItem}
   */
  @BuildStep
  VanillaBpAdapterDeploymentServiceBuildItem buildDeploymentServices() {

    return VanillaBpAdapterDeploymentServiceBuildItem
        .builder()
        .adapterType(Camunda8DeploymentService.ADAPTER_TYPE)
        .deploymentServiceBeanClass(Camunda8DeploymentServiceProducer.class.getName())
        .build();

  }

  /**
   * Registers the producer of the Camunda 8 adapter's process-service bean picked up by
   * the process-service beans generated by the VanillaBP Quarkus integration.
   *
   * @return The bean registration build item
   */
  @BuildStep
  AdditionalBeanBuildItem registerProcessServiceProducer() {

    // the process-service and deployment-service producers are registered by the
    // VanillaBP extension via the build items above - only the other producers are
    // registered here
    return AdditionalBeanBuildItem
        .builder()
        .addBeanClass(Camunda8ClientProducer.class)
        .addBeanClass(Camunda8StartupObserver.class)
        .setUnremovable()
        .build();

  }

  private static final String MICROMETER_EXTENSION_PROCESSOR = "io.quarkus.micrometer.deployment.MicrometerProcessor";

  /**
   * Registers the producer of this adapter's own meters - but only for an application
   * which uses Micrometer. The adapter does not bring it: metrics are the application's
   * decision, and an application without them has to boot unchanged.
   * <p>
   * The signal is the Micrometer extension's build-step class on the DEPLOYMENT
   * classpath, which is how the VanillaBP platform integration detects it as well. The
   * presence of Micrometer's own classes would not do - the Camunda client drags them in
   * as an optional dependency of its own, and nothing produces the {@code MeterRegistry}
   * the producer needs then.
   *
   * @param additionalBeans Producer used to register the metrics' producer
   */
  @BuildStep
  void registerMetricsProducer(
      final BuildProducer<AdditionalBeanBuildItem> additionalBeans) {

    try {
      Class.forName(
          MICROMETER_EXTENSION_PROCESSOR,
          false,
          Thread
              .currentThread()
              .getContextClassLoader());
    } catch (final ClassNotFoundException | LinkageError e) {
      return;
    }

    additionalBeans
        .produce(AdditionalBeanBuildItem
            .builder()
            .addBeanClass(Camunda8MetricsProducer.class)
            .setUnremovable() // applied by Micrometer's own startup, never injected
            .build());

  }

}
